apiVersion: v1
kind: Template
metadata:
  name: tf-serving-knative
  annotations:
    description: "Template to serve models using tensorflow and knative"
    openshift.io/display-name: "Tensorflow Serving (knative)"
    iconClass: "icon-python"
    tags: "opendatahub,tensorflow"
    openshift.io/provider-display-name: "Open Data Hub"
  labels:
    template: tf-serving-knative
objects:
- apiVersion: serving.knative.dev/v1alpha1
  kind: Service
  metadata:
    name: tf-serving-knative-${APP_NAME}
  spec:
    runLatest:
      configuration:
        revisionTemplate:
          metadata:
            annotations:
              # Target 10 in-flight-requests per pod.
              autoscaling.knative.dev/target: "${SCALE_FACTOR}"
              autoscaling.knative.dev/minScale: "1"
          spec:
            container:
              image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${IMAGE}:latest
              resources:
                limits:
                  memory: ${MEMORY}
                  cpu: ${CPU}
              env:
              - name: REVISION
                value: ${REVISION}
              - name: LOG_LEVEL
                value: ${LOG_LEVEL}
parameters:
- name: APP_NAME
  description: Short name of your application (to be used in OpenShift artifact names)
  value: demo
  required: true
- name: MEMORY
  description: Memory limit to be assigned to the job
  value: 1Gi
  required: true
- name: CPU
  description: Limit for number of cores to assign to the job
  value: "1"
  required: true
- description: Number of requests served by a single instance/pod
  name: SCALE_FACTOR
  value: "20"
- description: Namespace name the service is supposed to run in (probably current namespace)
  name: NAMESPACE
  value: tf-demo
- description: Image Stream name in the namespace to be used for deployment
  name: IMAGE
  value: tf-serving
- description: Version of the model
  name: REVISION
  value: "1"
- description: Log level
  name: LOG_LEVEL
  value: "WARNING"
