apiVersion: v1
kind: List
metadata:
  name: tf-serving
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      build: tf-serving
    name: tf-serving
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: tf-serving:latest
    source:
      git:
        uri: https://github.com/rhdemo/2019-demo4-ai
        ref: master
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: 'quay.io/vpavlin/python-36-ubi7:ubi'
      type: Source
    triggers:
    - type: ConfigChange
  status:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: tf-serving
    name: tf-serving
  spec:
    lookupPolicy:
      local: true
  status: